export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  ADMIN: 'ADMIN',
};

export const ACCOUNT_TYPES = {
  SAVINGS: 'Savings',
  CURRENT: 'Current',
};

export const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  FROZEN: 'FROZEN',
  CLOSED: 'CLOSED',
};

export const TRANSACTION_TYPES = {
  TRANSFER: 'TRANSFER',
  BILL_PAYMENT: 'BILL_PAYMENT',
  DEPOSIT: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
  REVERSAL: 'REVERSAL',
};

export const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
};

export const BILL_CATEGORIES = {
  ELECTRICITY: 'Electricity',
  WATER: 'Water',
  INTERNET: 'Internet',
  MOBILE: 'Mobile',
  CREDIT_CARD: 'Credit Card',
  INSURANCE: 'Insurance',
};

export const OTP_PURPOSES = {
  LOGIN: 'LOGIN',
  TRANSFER: 'TRANSFER',
  ADD_BENEFICIARY: 'ADD_BENEFICIARY',
  DELETE_BENEFICIARY: 'DELETE_BENEFICIARY',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
};

export const AUDIT_ACTIONS = {
  REGISTRATION: 'REGISTRATION',
  LOGIN: 'LOGIN',
  FAILED_LOGIN: 'FAILED_LOGIN',
  ACCOUNT_LOCKOUT: 'ACCOUNT_LOCKOUT',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  OTP_REQUEST: 'OTP_REQUEST',
  OTP_VERIFY_SUCCESS: 'OTP_VERIFY_SUCCESS',
  OTP_VERIFY_FAILED: 'OTP_VERIFY_FAILED',
  FUND_TRANSFER_SUCCESS: 'FUND_TRANSFER_SUCCESS',
  FUND_TRANSFER_FAILED: 'FUND_TRANSFER_FAILED',
  BENEFICIARY_CREATE: 'BENEFICIARY_CREATE',
  BENEFICIARY_UPDATE: 'BENEFICIARY_UPDATE',
  BENEFICIARY_DELETE: 'BENEFICIARY_DELETE',
  BILL_PAYMENT_SUCCESS: 'BILL_PAYMENT_SUCCESS',
  BILL_PAYMENT_FAILED: 'BILL_PAYMENT_FAILED',
  ACCOUNT_FREEZE: 'ACCOUNT_FREEZE',
  ACCOUNT_UNFREEZE: 'ACCOUNT_UNFREEZE',
  ADMIN_ACTION: 'ADMIN_ACTION',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
};
